language: java

jdk:
  - openjdk11

notifications:
  slack:
    secure: "i3w0giUwEmO2yWAHknaHfkV9jnDwmTLraUKBzEBD7nbaEosP6mStWVDNGQYmYcXEH8il/LqUPd9LovBqQt5rTKfih+lI2bT2YSlfPezWtRxxLQIb1WITiNxZXYVQRl78yKwIewRf+qvJm2J/rDTRxv5QAYup3aW9ANIZeQ50by4773vn4eSrzjBZbhynkEQ4WfLlL1MswsPs77wBZE7qXbLNuTQH2xGaNqXD8alz6gXUoE3XiJ+NH4iuguQhbp72wKEYcNCSnWXkC5//zcNzkBo8ZTyTIYg3Eet3WzvnIhX8nevZ4J3uEmUVilPCaD0mCfQdH8/wbDUNTef9NJh9IQepKOJ3LcLObmGWlPUJZLzgSHRzVjPcm9M8k5AHT+7LZCD0i4eUcjsAiKrhI5iqBoKqi1leSYGlcnAs++/EgJAFWJF++hA73Z3y0DnzvqZT2ju6Ik3YO2NeimGmvnXxFX9vCZpQk7pna6l1RBZuSEjfd9xZlLbRUX6n6UhYTyeJDHtxj3zaCw1KXmf1k7siScfDqHadi5q1KF4V9EcvskWMlFNDDSh2dS6j99LfFBHfZPxXDpLijCQhx1eUxXLXPIZcJjT6Yv+8X00yubq7LeDG/jERfJPEKvzMvJ8QGB0Yo3jBAl85z3rl7IqCM8YfgnmAtJqRa3Roa28VTV2L5iY="
