---
name: release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JVM
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish Package
        run: gradle clean build signMavenJavaPublication
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.JAR_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.JAR_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.JAR_SIGNING_SIGNING_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.OSSH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSH_TOKEN }}
      - name: Print out signed artifacts for testing
        run: |
          ls -la build/libs
          cat build/libs/dnsimple-java-0.9.3.jar.asc
          cat dnsimple-java-0.9.3-javadoc.jar.asc
          cat dnsimple-java-0.9.3-sources.jar.asc
